engines:
  eslint:
    enabled: true
    channel: 'eslint-3'

ratings:
  paths:
    - packages/structure/src/**

exclude_paths:
  - benchmark/**/*
  - packages/structure/dist/**/*
  - packages/structure/test/**/*
