language: node_js
node_js:
  - '8'
  - '10'
  - '11'
  - '12'
  - 'node'
before_script:
  - yarn test:browser:build
script:
  - yarn lint
  - yarn test
  - yarn test:browser:run
  - yarn run coveralls
